package com.hustleind.trash;

public class Replace {
    public static void main(String[] args) {
        String[] array = new String[] {"RC_TERM_INST_ID",
                "BILLING_SEQUENCE_NUMBER", "SPLIT_ROW_NUM", "SPLIT_OVER_ACCTS", "BILLING_ACCOUNT_NO", "PARENT_ACCOUNT_NO", "PARENT_SUBSCR_NO",
                "PARENT_SUBSCR_NO_RESETS", "OFFER_ID", "CONTRACT_USE_CODE", "BT_PROMOTION_PLAN_INST_ID", "FROM_DATE", "TO_DATE", "NUM_DAYS",
                "CYCLE_FROM_DATE", "CYCLE_TO_DATE", "APPLY_DATE", "CREATE_DATE", "RC_INST_START_DATE", "PCM_ACTIVE_DT", "EXPECTED_CUTOFF_DT",
                "PRORATE_CODE", "BASE_AMT", "PRORATED_AMOUNT", "AMOUNT", "AMOUNT_POSTPAID", "AMOUNT_PREPAID", "ISO_CODE", "POP_UNITS",
                "POP_UNIT_TYPE", "HAS_OVERRIDES", "RC_TERM_ID", "JURISDICTION", "BALANCE_COUNT", "GEOCODE", "TAX_PKG_COUNT", "TOTAL_TAX",
                "TOTAL_TAX_POSTPAID", "TOTAL_TAX_PREPAID", "TOTAL_FEDERAL_TAX", "TOTAL_STATE_TAX", "TOTAL_COUNTY_TAX", "TOTAL_CITY_TAX",
                "TOTAL_OTHER_TAX", "ALL_TAX_CALC", "NUM_BILLED_LINES", "NUM_TRUNK_LINES", "TAX_TYPE_CODE", "COMMITMENT_AMOUNT",
                "BUNDLE_ID", "UNITS", "UNIT_TYPE", "PROVISIONED_AWARD_COUNT", "RATED_CURRENCY_CODE", "RATED_BY_SINGLE_VERSION",
                "RC_INST_END_DATE", "IS_BILLABLE", "CREATE_DATE_SUB_TZ", "TIMEZONE", "MOG_ID", "FREQUENCY", "BALANCE_INFO", "ACCUMULATOR_INFO",
                "RC_TERM_NAME", "SERVICE_EXTERNAL_ID", "IS_SERVICE_ITEM", "FILENAME", "SDP"};

        for (String s : array) {
            System.out.println(s + " string,");
        }
    }
}
