package com.hustleind.trash;

public class TempClass {
    public static void main(String[] args) {
        String[] input = new String[] {"EXTERNAL_ID", "TRANS_ID_1", "TRANS_ID_2", "DATE_TIME", "SUBSCRIBER_TYPE", "MESSAGE_TYPE",
                "SUB_ID2", "REFUND_FLAG", "GROUP_ACCOUNT_TYPE", "APPLICATION_ID", "SUBTYPE_ID", "UNIT_TYPE_ID", "TYPE_OF_CHARGE", "USAGE_AMOUNT",
                "CHARGE_CODE", "CONTENT_TYPE", "SERVICE_CODE", "ORP_DATE_1", "FUND_USAGE_TYPE", "SUBSCRIBER_CURRENCY", "CURR_CONV_RATE",
                "REQUESTED_ISO_CODE", "MSC_ID", "CIRCLE_ID", "MOG_ID", "BAL_INFO", "ACCU_INFO", "EXT_FIELD", "GROUP_ACCOUNT_INFO",
                "ORP_DATE_2", "RECORD_SOURCE", "ACCT_BAL_INFO", "ACCT_ACCU_INFO", "LIABILITY_REDIRECT_INDICATOR", "USER_SUBSCR_NO",
                "USER_SUBSCR_NO_RESETS", "TARGET_SUBSCR_NO", "TARGET_SUBSCR_NO_RESETS", "SUBSCR_NO", "SUBSCR_NO_RESETS", "ACCOUNT_NO",
                "INITIAL_AUT_ID", "FINAL_AUT_ID", "PARENT_ACCOUNT_NO", "SPLIT_ROW_NUM", "MSG_ID2", "MSG_ID", "SLU_ID", "RESELLER_ID",
                "EXTERNAL_ID_TYPE", "PREV_ISO_CODE", "GSM_PROVIDER_ID", "PRE_CHARGE", "MARKUP_PERCENT", "CONV_RATE_TO_BILLED_ACCT",
                "BILLED_ACCOUNT_CURRENCY", "BILLED_ACCOUNT_TML_CHANGE", "BILLED_ACCOUNT_TML_VALUE", "TIMEZONE", "ROUNDED_DURATION",
                "DATE_TIME_SUB_TZ", "TARIFF_PLAN_ID", "ORIG_TARIFF_PLAN_ID", "USAGE_OFFER_ID",
                /*Добавлено по задаче DMP-812*/
                "NEW_BALANCE1", "NEW_BALANCE2", "NEW_BALANCE3", "NEW_BALANCE4", "NEW_BALANCE5", "NEW_BALANCE6", "NEW_BALANCE7",
                "NEW_BALANCE8", "NEW_BALANCE9", "NEW_BALANCE10", "NEW_BALANCE11", "NEW_BALANCE12", "NEW_BALANCE13", "NEW_BALANCE14",
                "NEW_BALANCE15", "NEW_BALANCE16", "NEW_BALANCE17", "NEW_BALANCE18", "NEW_BALANCE19", "NEW_BALANCE20", "NEW_BALANCE21",
                "NEW_BALANCE22", "NEW_BALANCE23", "NEW_BALANCE24", "NEW_BALANCE25", "NEW_BALANCE26", "NEW_BALANCE27", "NEW_BALANCE28",
                "NEW_BALANCE29", "NEW_BALANCE30", "CHANGE_AMOUNT1", "CHANGE_AMOUNT2", "CHANGE_AMOUNT3", "CHANGE_AMOUNT4", "CHANGE_AMOUNT5",
                "CHANGE_AMOUNT6", "CHANGE_AMOUNT7", "CHANGE_AMOUNT8", "CHANGE_AMOUNT9", "CHANGE_AMOUNT10", "CHANGE_AMOUNT11", "CHANGE_AMOUNT12",
                "CHANGE_AMOUNT13", "CHANGE_AMOUNT14", "CHANGE_AMOUNT15", "CHANGE_AMOUNT16", "CHANGE_AMOUNT17", "CHANGE_AMOUNT18", "CHANGE_AMOUNT19",
                "CHANGE_AMOUNT20", "CHANGE_AMOUNT21", "CHANGE_AMOUNT22", "CHANGE_AMOUNT23", "CHANGE_AMOUNT24", "CHANGE_AMOUNT25", "CHANGE_AMOUNT26",
                "CHANGE_AMOUNT27", "CHANGE_AMOUNT28", "CHANGE_AMOUNT29", "CHANGE_AMOUNT30",
                "FILENAME", "SDP"};
        for (String s : input) {
            System.out.println(s + " string,");
        }
    }
}
